// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;

/**
 * Resolve and validate Supabase configuration from environment variables.
 *
 * - Uses `VITE_SUPABASE_URL` directly when present.
 * - Falls back to building the URL from `VITE_SUPABASE_PROJECT_ID` if needed.
 * - Ensures the publishable (anon) key is present; throws a descriptive error otherwise.
 *
 * @returns An object containing `url` and `key` to initialize the client.
 */
function getSupabaseConfig(): { url: string; key: string } {
  const url = SUPABASE_URL || (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : "");
  const key = SUPABASE_PUBLISHABLE_KEY || "";

  if (!url) {
    throw new Error("Supabase URL não definido. Configure VITE_SUPABASE_URL ou VITE_SUPABASE_PROJECT_ID no .env.");
  }
  if (!key) {
    throw new Error("Supabase anon key não definido. Configure VITE_SUPABASE_PUBLISHABLE_KEY no .env.");
  }

  return { url, key };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const { url: resolvedUrl, key: resolvedKey } = getSupabaseConfig();

export const supabase = createClient<Database>(resolvedUrl, resolvedKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});